### ISSUE TITLE
Disabled Nav Item

### ISSUE THREAD

**Issue by rfaloisio** [coreui/coreui-free-react-admin-template#106]
Hey Guys!

Is there a navItem prop that makes it unclickable/disabled?

Thanks in advance!

**Comment by jeff-nz** [comment]
Hi @rfaloisio ,

> Is there a navItem prop that makes it unclickable/disabled?

This is reactstrap question but i'll try my best to help out.

Yes and no.
I don't think there is a property to disable NavItem at the moment.
However, you can still make the link not clickable by adding the "disabled" attribute into NavLink instead of NavItem.

The code might look something like:

```
<NavItem className="px-3">
    <NavLink href="/users" disabled>Users</NavLink>
</NavItem>
```

or check this link out:

https://reactstrap.github.io/components/navs/

I hope it helps.

**Comment by xidedix** [comment]
hi @rfaloisio @Haziqasyraff 

please update:
- `@coreui/coreui` to `2.1.0`
- `@coreui/react` to `2.1.0`

usage example (_nav.js): 
```js
    {
      name: 'Disabled',
      url: '/dashboard',
      icon: 'icon-ban',
      attributes: { disabled: true },
    },
```

and let us know if it works for you
