### ISSUE TITLE
How to make plain create-react-app work with CoreUI

### ISSUE THREAD

**Issue by vmundhra** [coreui/coreui-free-react-admin-template#14]
You say its bootstrapped with create-react-app but looks like many libraries are different in both. Can you give a simple method, to start with the latest create-react-app and then add on the libraries to make CoreUi work?

Would be very helpful and not confusing to others.

Thanks.

**Comment by BrandonClapp** [comment]
It's likely that he ejected the default scaffold of create-react-app. I see the `webpack.config.js` in the root directory, as well as the `scss` resources referenced as relative path in the root directory rather than in `src`.

I'm new to create-react-app and I agree, it was confusing to me, as well.

**Comment by thangchung** [comment]
@vmundhra I have been doing it at #31. It works well, hopes this can shed a light for you a bit :)

**Comment by xidedix** [comment]
please take a look at [https://github.com/mrholek/CoreUI-React/tree/v2.0.0](https://github.com/mrholek/CoreUI-React/tree/v2.0.0) - it is a work in progress but shows direction we are heading.

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above. Please comment and/or reopen if you feel the issue has not been resolved.
