### ISSUE TITLE
3.0?

### ISSUE THREAD

**Issue by FlyingTigerReally** [coreui/coreui-free-react-admin-template#205]
When will 3.0 be released?

**Comment by ccamacho** [comment]
@FlyingTigerReally I have been waiting for this since January, I'm starting to see other options[1] I managed to replace it pretty much completely. So I recommend you give a deadline as v3 was supposed to be released in December[2], not sure now if v3 will be released now, soon or never xD

In particular, I liked airframe because it supports ReCharts and the design it's pretty slick.

[1]: https://github.com/0wczar/airframe-react 
[2]: https://github.com/coreui/coreui/issues/74#issuecomment-570063619

**Comment by timonbimon** [comment]
Is this still being maintained? It seems like the last commit dates back quite some time ago...

**Comment by Letrab** [comment]
I thought as well that this was unmaintained. But apparently work is being done on CoreUI3 (Pro) for React:

https://www.npmjs.com/package/@coreui/react/v/3.0.0-alpha.5

There is no example/documentation yet, but it's in alpha.

**Comment by johnnytolengo** [comment]
When will  CoreUI3 (Pro) for React be released?  It seems to be a new for a looong time. I also asked via the support Form 2 weeks  ago without reply (48hs seems to be not true).
hopeless..

**Comment by Letrab** [comment]
Just got a mail: Free CoreUI for React.js v3.0.0-alpha.1 is live and released!

Upcoming this month as well: CoreUI for React.js v3.0.0-beta

**Comment by JoHuang** [comment]
Any news? If I bought React pro version, will I get the React v3 template?

**Comment by johnnytolengo** [comment]
Yes!

**Comment by JoHuang** [comment]
Do you have plan to release the React V3 template to this repo?

**Comment by woothu** [comment]
V3 is released!
