### ISSUE TITLE
Datepicker input field trigger calender show

### ISSUE THREAD

**Issue by michaeldino27** [coreui/coreui-free-react-admin-template#266]
Hello,

I've started using this template for my client and been requested to show the calendar selection when they click in any part of the date field not just the calendar icon, i went looking at the documentation regarding this feature but have not seen any, i also went to the issues if any have had this concern but no luck.
Would really appreciate if there is an existing function to make this happen. 

Thanks a lot.
Regards,
Michael Dino

**Comment by Dimondevelop** [comment]
I ran into the same problem. Why is there no answer?

**Comment by mrholek** [comment]
@Dimondevelop First of all, for PRO products, we have a dedicated support form—https://coreui.io/support/. However, in 2020, we didn't have our date picker component in our PRO templates; we used third-party plugins.

Currently, this problem does not exist because we have our own component - https://coreui.io/react/docs/forms/date-picker/. You can click on the calendar icon or the date, and the calendar will be shown.
